### PR TITLE
Update for Ubuntu 16 and 18

### PR DESCRIPTION
**Pull request by petey2144**
fixes issue #1 

I may have introduced some odd wording of my own here, so I may re-write some sections of it later for clarity.

### CODE REVIEW

**Review by cticenhour — COMMENTED** [review]
What is the deal with this #xpdp1_install_guide_LINUX.tex# file that shows up as a changed file? Did this get added in your commits somewhere?

**Comment by cticenhour** [comment]
Actually this might have come from some weirdness with pushing up to github from the terminal...

**Comment by cticenhour** [comment]
In the future, try to make a branch on your fork, from the master branch, and then working in that. That should keep repeat commits from happening and muddying up the commit history. Highly recommend looking at Atlassian tutorials for git for future reference.

**Comment by petey2144** [comment]
Yeah I'm not sure where it came from, it might have been a temporary file that got committed from texstudio still being open while making commits. Yeah I found that guide that after I had already made two commits...will do from now on. Rookie mistake!

**Comment by cticenhour** [comment]
No worries! I couldn't make heads or tails of this stuff when I started. I'm going to merge this and then fix it.

**Pull request merged**
